export { default as Question13 } from './Question-13'
export { default as Question19 } from './Question-19'
export { default as Question26 } from './Question-26'
export { default as Question29 } from './Question-29'
export { default as Question34 } from './Question-34'
